---
title       : GitHub Pages
subtitle    : 
author      : 
job         : 
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## <h1>Github Pages</h1>
<h3>8/31/2015</h3>

---

## What are Github Pages?

GitHub Pages are public webpages hosted and published through Github.

- User Pages : One per user account. http://username.github.io/. Content from the master branch will be used to build and publish your GitHub Pages site.
- Project Pages : One per repository. http://username.github.io/projectname. The gh-pages branch is used to build and publish Project Pages sites.
- Warning: GitHub Pages sites are publicly available on the internet, even if their repositories are private.

---

## What are Github Pages? - continued

- You can use GitHub's [Automatic Page Generator](https://help.github.com/articles/creating-pages-with-the-automatic-generator/) to quickly create a website for a project, user, or organization.

- You can set up a [custom domain](https://help.github.com/articles/about-custom-domains-for-github-pages-sites/) with GitHub Pages.

---

## Creating User Pages

- Create a new repository use your account name in **username.github.io** format. 
- For new website, use the Automatic Page Generator to create the site, or
- Clone the repository, then create an index.html file in username.github.io folder.
- For existing website, copy existing files to username.github.io folder.
- Commit and push the files.
- View GitHub pages at http://username.github.io/.

---

## Creating Project Pages

- Create a new repository or use an existing repository.
- Create a new branch called gh-pages.
- For new website, use the Automatic Page Generator to create the site, or
- Create an index.html page in projectname folder.
- For existing website, copy existing files to projectname folder.
- Commit and push the files.
- View GitHub Pages at http://username.github.io/projectname/
- These slides are GitHub Project Pages.

---

## Using Jekyll with Pages

- In addition to supporting regular HTML content, GitHub Pages support Jekyll, a simple, blog-aware static site generator.
- Jekyll makes it easy to create site-wide headers and footers without having to copy them across every page.
- Every GitHub Page is run through Jekyll when you push content to a specially named branch within your repository.
- Because a normal HTML site is also a valid Jekyll site, you don't have to do anything special to keep your standard HTML files unchanged.

---

## Using Jekyll with Pages - continued
- GitHub recommends installing Jekyll on your computer to preview your site and help diagnose troubled builds before publishing your site on GitHub Pages.
- For more information on installing Jekyll: https://help.github.com/articles/using-jekyll-with-pages/
- Jekyll isn’t officially supported on Windows, but [it is still possible to run it](http://jekyllrb.com/docs/windows/#installation) if you&#39;re prepared to get your hands dirty.
- To know more about Jekyll, visit http://jekyllrb.com/

---

## Setting up a custom domain with GitHub Pages
GitHub provides step-by-step instructions on how to set up a custom domain with your GitHub Pages. 
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

---

## Useful links:
- http://pages.github.com
- https://help.github.com/categories/github-pages-basics/
- https://github.com/github/pages-gem
- https://github.com/Shopify/liquid/wiki
- https://github.com/jekyll/jekyll
- http://jekyllrb.com/
- http://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/